# Generated by Django 5.1.4 on 2025-01-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas_Camping_SD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campista',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservas_Camping_SD.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservas_Camping_SD.usuario'),
            preserve_default=False,
        ),
    ]
